<?php 
defined('BASEPATH') OR exit('No direct script access allowed');

return array(
	'dir' => "文件夹",
	'gif' => "GIF 图像",
	'htm' => "HTML Document",
	'html' => "HTML Document",
	'shtml' => "shtmlfile",
	'php' => "php 脚本",
	'asp' => "Active Server Page",
	'do' => "DO 文件",
	'swf' => "Shockwave Flash Object",
	'xml' => "XML 文档",
	'jpg' => "JPEG 图像",
	'jpeg' => "JPEG 图像",
	'png' => "PNG 图像",
	'bmp' => "BMP 图像",
	'tif' => "TIF 文件",
	'js' => "JavaScript 文件",
	'doc' => "Microsoft Word 文档",
	'docx' => "Microsoft Word 文档",
	'mp3' => "MP3 格式声音",
	'mp4' => "MP4 格式视频",
	'rar' => "WinRAR 压缩文件",
	'psd' => "Adobe Photoshop Image",
	'pdf' => "Adobe Acrobat 7.0 Document",
	'zip' => "WinRAR ZIP 压缩文件",
	'rm' => "RealMedia",
	'rmvb' => "RealVideo VBR",
	'wav' => "波形声音",
	'mid' => "MIDI 序列",
	'midi' => "MIDI 序列",
	'mpg' => "电影剪辑",
	'mpeg' => "电影剪辑",
	'asf' => "Windows Media 音频/视频文件",
	'asx' => "Windows Media 音频/视频播放列表",
	'mov' => "QuickTime 影片",
	'xls' => "Microsoft Excel 工作表",
	'chm' => "已编译的 HTML 帮助文件",
	'hlp' => "帮助文件",
	'exe' => "应用程序",
	'txt' => "文本文档",
	'other' => "未知",
);
?>